# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0683c0f9bcd01f64a41742cccc1ee99d5eaa441aa85333184f9c48296b17b85feefbc70df5b9a708430fe4a723e5e530937657b44af04a7a494b5c82e08be99

test:
  secret_key_base: 767002c81f4a18cf9d7d03ee454848066d647ad44e4c649acce1fa98449324367ebd56704c3138198d0f83a60c60a662ad13621a6432134a92b86e2e984b0034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
