# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe573519076a1c9b10edf4d251ddc43590ffa07e177b78ae07d26cd463d976cec7c707c6c8180c4607e1c204ca702b6f926f537c1e8ea02ac06d262febbad60

test:
  secret_key_base: 1cbe5f39c6dd1a0628bac7fc28a6c2e0591e249772a72e7df3d79c924de450cf472c17e2a619c04907bab9a182a20c71edae42896ce29fefbd10225300157c2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
